- src/bin/TutorialD/Interpreter/Base.hs
The `void` operator does exist in older versions of
Control.Monad. Removing this constraint allows stack based builds to
occur successfully under lts-6.27.
> Removed CPP restriction on Control.Monad

- src/lib/ProjectM36/Client.hs
If you intentionally left this out of the export list, then just close this PR. However, I thought it was likely an oversight since `Client` does export `executeDatabaseContextIOExpr` which uses this type.
> Export DatabaseContextIOExpr from Client

- project-m36.cabal
The `project-m36 == 0.1` constraint produces a cabal warning.
> Remove needless version constraint on the local package

- project-m36.cabal
- src/bin/ProjectM36/Server/RemoteCallTypes/Json.hs
This makes project-m36 *mostly* compatible with LTS 9.3.
Aeson 1.1 and above includes non-orphan instances of UUID types. `uuid-aeson` was simply providing these instances so it is no longer needed.
> Drop uuid aeson

- src/lib/ProjectM36/Client/Simple.hs
The module description haddock comment was in the wrong place, causing haddock to fail. I suppose this is also true of the version 0.2 released on hackage, and that's why there are no docs there yet? Would it be worth cutting another release just to fix the docs?
> fix haddock of ProjectM36.Client.Simple

- docs/using_notifications.markdown
- src/bin/ProjectM36/Server/WebSocket/project-m36.js
- src/bin/ProjectM36/Server/WebSocket/websocket-client.js
- src/bin/TutorialD/Interpreter.hs
- src/bin/TutorialD/Interpreter/DatabaseContextExpr.hs
- src/lib/ProjectM36/Base.hs
- src/lib/ProjectM36/Client.hs
- src/lib/ProjectM36/Notifications.hs
- src/lib/ProjectM36/RelationalExpression.hs
- src/lib/ProjectM36/StaticOptimizer.hs
- test/Server/Main.hs
- test/TutorialD/Interpreter.hs
This patch allows notifications to carry two relational expressions for evaluation: one to be evaluated in the pre-change context and one to be evaluated in the post-change context. The expressions need not be identical. I used `true` as a placeholder for a no-op, but that could be improved.
> make notification old/new expression distinction explicit

- examples/blog.hs
- project-m36.cabal
The blog example has been augmented with a scotty-based web interface as a demonstration of how Haskell data types can be easily marshalled between the database and back.
In this case, we have two data types: `Blog` and `Comment` where blogs are in a one-to-many relationship with comments.
Are there things here I could simplify to make it more accessible to newcomers?
> Blog web example

- README.markdown
- docs/reaching_out_of_the_tarpit.markdown
Hi there,
The current links to the "tarpit.pdf" paper seem to be dead (at the time of this writing, anyway).
I've gone ahead and replaced them.
http://shaffer.us -> https://github.com/papers-we-love/papers-we-love
I've hard-coded the new link's git ref to 2eb8d21 in case they remove the paper in a later version of the repo.
Thanks for `project-m36`!
> Replace dead link to `tarpit.pdf`

- .appveyor.yml
- README.markdown
- src/lib/ProjectM36/FileLock.hs
- src/lib/ProjectM36/Persist.hs
- src/lib/ProjectM36/ScriptSession.hs
- src/lib/ProjectM36/TransactionGraph.hs
O, the irony- after the endless travis hurdles, appveyor is trivial. 
Appveyor's VMs are able to build Project:M36 without any caching in 22 minutes (60 minutes maximum) which suggests that travis' VMs are comparatively underpowered. 
I need to fix the pkgdb path and some seemingly broken packages- I'm not sure what that is about- but the basics are in place.
> Appveyor builder

- src/lib/ProjectM36/Atomable.hs
Running the blog example triggered the following exception when using CrashSafePersistence and trying to submit a comment from the web interface:
```UnhandledExceptionError "primitive type missing: TextAtomType\nCallStack (from HasCallStack):\n error, called at ./src/lib/ProjectM36/Atomable.hs:232:39 in project-m36-0.3-AaOlZo5ZXxJ9qLXdxcn1Yt:ProjectM36.Atomable"```
This PR fixes that.
> Fix primitiveATypeName lookup

- cbits/DirectoryFsync.c
When using CrashSafePersistence each transaction would leak 2 file descriptors, i.e:
```
mydb/heads
mydb/e580ab4e-b4cf-433f-a819-d6d00e2e773c
```
> Close file descriptor in syncDirectory

- src/bin/TutorialD/Interpreter/RelationalExpr.hs
- src/lib/ProjectM36/Base.hs
- src/lib/ProjectM36/RelationalExpression.hs
- src/lib/ProjectM36/StaticOptimizer.hs
I've made a first pass, using the relation expression state.
I use AS instead of := at a first pass just try to help me implement it from SQL WITH. However, It can be changed for any good reason.
It supports multiple views. However, it can only reference previous ones.
```
TutorialD (master/main): :importexample date
TutorialD (master/main): :showexpr WITH (a AS s{s#,city}, b AS a{city}) b
┌──────────┐
│city::Text│
├──────────┤
│"Paris"   │
│"London"  │
│"Athens"  │
└──────────┘
```
> add with macro with multiple views

- docs/atomfunctions.markdown
I take out one `\`, then the first example works!
> make first example work.

- docs/tutd_tutorial.markdown
And the `S` relvar is in fact `s`.
> Types section requires date example to be loaded

- docs/tupleable.markdown
- examples/DerivingCustomTupleable.hs
- project-m36.cabal
- src/lib/ProjectM36/Tupleable.hs
- src/lib/ProjectM36/Tupleable/Deriving.hs
- test/Relation/Tupleable.hs
Takes advantage of the DerivingVia extension to allow for deriving Tupleable instances with custom options. Note that the type of `toAttributes` is changed from `proxy a -> Attributes` to `Proxy a -> Attributes`
fixes #163
> Add support for deriving Tupleable instances with custom options.

- docs/introduction_to_the_relational_algebra.markdown
The column names didn’t match.
> Fixed typo in introduction_to_the_relational_algebra.markdown

- src/lib/ProjectM36/AtomFunctions/Primitive.hs
We had `int :: Integer -> Int` and were missing the opposite
> Added 'integer' atom function

- src/lib/ProjectM36/Client.hs
- src/lib/ProjectM36/DisconnectedTransaction.hs
This time, If I `createarbitraryrelation a {a Int} 1000000-1000000` and `:commit` twice, I have only one large transaction in disk.
The space usage should grow much slower.
> load GraphRefRelVars instead of real expressions

- hie.yaml
Auto generated via:
```
> stack install implicit-hie
> gen-hie > hie.yaml
```
then changed cradle type (line 2) from cabal to stack.
> Added hie.yaml, fixes HLS problems

- docs/tutd_tutorial.markdown
- release.nix
- src/lib/ProjectM36/Relation/Parse/CSV.hs
allow csv TextAtom parser to accept parens and commas in order to accept descriptions like "abc(abc)" or "a, b, c"
> Csv parse text with parens and commas
